### ISSUE TITLE
*SyntaxError: Unexpected token (580:263) with new version of constantinople

### ISSUE THREAD

**Issue by joynexa** [pugjs/constantinople#5]
Hi

We have started getting the following error in our application for last few days(approx 5 days)..

**SyntaxError: Unexpected token (580:263)
    at Parser.pp$4.raise (../../node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:2488:13)
    at Parser.pp.unexpected ../../node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:623:8)
    at Parser.pp.expect (../../node_modules/acorn/dist/acorn.js:617:26)
    at Parser.pp$3.parseExprList (../../node_modules/acorn/dist/acorn.js:2406:14)
    at Parser.pp$3.parseSubscripts ../../node_modules/acorn/dist/acorn.js:1900:29)
    at Parser.pp$3.parseExprSubscripts (../../node_modules/acorn/dist/acorn.js:1875:21)
    at Parser.pp$3.parseMaybeUnary ../../node_modules/acorn/dist/acorn.js:1849:17)
    at Parser.pp$3.parseExprOp ../../node_modules/acorn/dist/acorn.js:1810:41)
    at Parser.pp$3.parseExprOp (../../node_modules/acorn/dist/acorn.js:1812:19)
    at Parser.pp$3.parseExprOp (../../node_modules/acorn/dist/acorn.js:1812:19)
    at Parser.pp$3.parseExprOps (../../node_modules/acorn/dist/acorn.js:1793:15)
    at Parser.pp$3.parseMaybeConditional (../../node_modules/acorn/dist/acorn.js:1774:19)
    at Parser.pp$3.parseMaybeAssign (../../node_modules/acorn/dist/acorn.js:1750:19)
    at Parser.pp$3.parseParenAndDistinguishExpression (../../node_modules/acorn/dist/acorn.js:2056:30)
    at Parser.pp$3.parseExprAtom (../../node_modules/acorn/dist/acorn.js:1978:41)
    at Parser.pp$3.parseExprSubscripts (../../node_modules/acorn/dist/acorn.js:1872:19)
    at Parser.pp$3.parseMaybeUnary (../../node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:1849:17)
    at Parser.pp$3.parseExprOp (/../../node_modules/acorn/dist/acorn.js:1810:41)
    at Parser.pp$3.parseExprOp (../../node_modules/acorn/dist/acorn.js:1812:19)
    at Parser.pp$3.parseExprOps (../../node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:1793:15)
    at Parser.pp$3.parseMaybeConditional (../../node_modules/acorn/dist/acorn.js:1774:19)
    at Parser.pp$3.parseMaybeAssign (../../node_modules/acorn/dist/acorn.js:1750:19)
    at Parser.pp$3.parseMaybeAssign (../../node_modules/acorn/dist/acorn.js:1761:23)
    at Parser.pp$3.parseExpression (../../node_modules/acorn/dist/acorn.js:1722:19)
    at Parser.pp$1.parseStatement (../../node_modules/acorn/dist/acorn.js:777:45)
    at Parser.pp$1.parseBlock (../../node_modules/acorn/dist/acorn.js:1040:23)
    at Parser.pp$1.parseStatement (../../node_modules/acorn/dist/acorn.js:754:31)
    at Parser.pp$1.parseIfStatement (../../node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:879:26)**

Getting this error with 3.1.2 version of constantinople. However if I replace with with an earlier version of the module, the error goes away.

Could you please suggest what could be the issue ..?

Thanks ..

**Comment by ForbesLindesay** [comment]
This looks like you're attempting to parse the constantinople code using acorn? I don't see an obvious reason why that shouldn't' work, but it possibly depends on the version of acorn you're using and whether you've configured acorn to use ES6.  I can't tell where the issue actually is though - constantinople doesn't appear anywhere in that stack trace so I don't really have anywhere to start.
